services:
  - type: web
    name: text-leech-bot-web
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: WEBHOOK
        sync: false
      - key: PORT
        value: 8000

  - type: worker
    name: text-leech-bot-worker
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    startCommand: "python3 modules/main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
